language: java
jdk:
       - openjdk17

branches:
        only:
                - master
cache:
        directories:
                - '$HOME/.m2/repository'
                - '$HOME/.gradle'

before_install: 
        - chmod +x gradlew

before_deploy:
        - mkdir -p before-deploy
        - cp scripts/*.sh before-deploy/
        - cp appspec.yml before-deploy/
        - cp build/libs/*.jar before-deploy/
        - cd before-deploy && zip -r before-deploy *
        - cd  ../ && mkdir -p deploy  
        - mv before-deploy/before-deploy.zip deploy/metastandard.zip

deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: metastandard-deploy
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: deploy
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: metastandard_deploy
          key: metastandard.zip
          bundle_type: zip
          application: metastandard
          deployment_group: metastandard-group
          region: ap-northeast-2
          wait_until_deployed: true  
 
script: "./gradlew clean build"
notifications:
        email:
                recipients:
                        - 'ohho28@gmail.com'
