version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step2/zip/
    overwrite: yes

  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
        ApplicationStart:
                - location: deploy2.sh
                  timeout: 60
                  runas: ubuntu
